apiVersion: 1
deleteDatasources: []
datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://240.0.0.5:9090
    basicAuth: false
    isDefault: true
    readOnly: false
    jsonData: 
      httpMethod: "POST"
      tlsSkipverify: true
