global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus_postgresql_adapter
    static_configs:
      - targets: ["240.0.0.3:9187"]
  - job_name: prometheus
    static_configs:
      - targets: ["240.0.0.5:9090"]
